---
ID: "099fb822-6741-49e7-b1b0-2f561cd2469a"
Parent: "15d44672-60a1-4636-8e13-b42e37935404"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: "/sitecore/content/xmc-cl/xmccomponentlibrary/Presentation/Headless Variants/Navigation/Default"
BranchID: "70519928-c595-4b2b-bb35-75022feecc4c"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{25F1A8E5-EB4C-4202-A9F7-A97DB52DA9AF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250213T202857Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\richard.seal@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\richard.seal@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "06ec4efb-9e5a-4f68-b24b-ec37ca7c8d21"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\richard.seal@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250213T202857Z
