---
ID: "c5bf35b2-2463-4304-8327-0112142d7e0d"
Parent: "9dbe8119-926f-400a-a738-6f3a43f86f75"
Template: "7ee0975b-0698-493e-b3a2-0b2ef33d0522"
Path: "/sitecore/layout/Renderings/Project/click-click-launch/Product"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250319T171907Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\alex.jackson@velir.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\alex.jackson@velir.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "73636efa-dff3-45ba-b46e-4aa44b26107e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\alex.jackson@velir.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250319T171907Z
